name: NodeJS with NPM and Grunt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 16.x, 18.x]
        python-version: [3.9.x, 3.10.x, 3.11.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache APT Packages
      uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      with:
        packages: "build-essential uuid-dev"

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: v1-npm-deps-

    - name: Build
      run: |
        npm install
        npm run setup-mac-keychain
        npm run lint
        DEBUG=electron-packager,electron-osx-sign npm run build
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: First interaction
      uses: actions/first-interaction@v1.1.1
      with:
        # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: ${{ github.token }}
        issue-message: |
          Hello! Thank you for filing an issue.
          
          Please include relevant logs or detailed description for faster resolutions.
          
          We really appreciate your contribution! 
          
          Thanks
        pr-message: |
          Hello! Thank you for your contribution.
          
          If you are fixing a bug, please reference the issue number in the description.
          
          If you are implementing a feature request, please check with the maintainers that the feature will be accepted first.
          
          We really appreciate your contribution!
          
          Thanks 
